name: doc_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #Flutter Widgets that make it easy to implement the BLoC (Business Logic
  flutter_bloc: ^8.1.3
  #Code generation(used mainly with cubit &API service) for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  #for Dependencies injection
  get_it: ^7.6.4
  #Classes and helper functions that support JSON code generation
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  #Networking
  #A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc
  dio: ^5.4.0
  #retrofit.dart is an dio client generator
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  #Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  #Easy and Fast internationalizing and localization your Flutter Apps
  easy_localization: ^3.0.3
  #Contains code to deal with internationalized/localized messages, date and number formatting and parsing
  intl: ^0.18.1
  #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9
  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
